// Dữ liệu mẫu để khởi tạo hệ thống lần đầu chạy (khi API/local rỗng)
export const seedProviders = [
  {
    id: "p1",
    name: "Hanoi Auto Rentals",
    email: "provider1@morent.vn",
    password: "123456",
    phone: "0901234567",
    status: "active",
    createdAt: "2026-01-10",
  },
  {
    id: "p2",
    name: "Saigon Wheels Co.",
    email: "provider2@morent.vn",
    password: "123456",
    phone: "0912345678",
    status: "active",
    createdAt: "2026-02-14",
  },
  {
    id: "p3",
    name: "Danang Luxury Car",
    email: "provider3@morent.vn",
    password: "123456",
    phone: "0934567890",
    status: "active",
    createdAt: "2026-03-01",
  },
];

export const seedCustomers = [
  {
    id: "c1",
    name: "Nguyễn Việt Anh",
    email: "customer1@morent.vn",
    password: "123456",
    phone: "0987654321",
    address: "Thanh Xuân, Hà Nội",
    createdAt: "2026-03-01",
  },
  {
    id: "c2",
    name: "Trần Minh Hoàng",
    email: "hoangtm@gmail.com",
    password: "123456",
    phone: "0971234567",
    address: "Quận 1, TP. Hồ Chí Minh",
    createdAt: "2026-03-10",
  },
];

export const seedVehicles = [
  {
    id: "v1",
    providerId: "p1",
    name: "Toyota Vios G 2024",
    brand: "Toyota",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 70000,
    pricePerDay: 650000,
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Xe gia đình nhỏ gọn, tiết kiệm xăng vượt trội (5.8L/100km), trang bị màn hình Apple CarPlay, cảm biến lùi, camera lùi.",
    features: ["Apple CarPlay / Android Auto", "Camera lùi & cảm biến", "7 Túi khí an toàn", "Cruise Control"],
    status: "approved",
    rating: 4.8,
  },
  {
    id: "v2",
    providerId: "p1",
    name: "Toyota Camry 2.5Q 2024",
    brand: "Toyota",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 150000,
    pricePerDay: 1400000,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Sedan doanh nhân đẳng cấp, êm ái tuyệt đối, ghế chỉnh điện nhớ vị trí, cửa sổ trời, dàn âm thanh 9 loa JBL cao cấp.",
    features: ["Âm thanh JBL cao cấp", "Cửa sổ trời", "Camera 360", "Hàng ghế thương gia ngả điện"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v3",
    providerId: "p2",
    name: "Toyota Fortuner Legender 2023",
    brand: "Toyota",
    type: "SUV",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Dầu diesel",
    pricePerHour: 140000,
    pricePerDay: 1300000,
    image: "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "SUV 7 chỗ gầm cao mạnh mẽ, máy dầu tiết kiệm và bền bỉ, thích hợp đi công tác xa, du lịch đồi núi và đại gia đình.",
    features: ["Hệ dẫn động 4x4", "Gói an toàn Toyota Safety Sense", "Cốp điện rảnh tay", "Camera 360"],
    status: "approved",
    rating: 4.7,
  },
  {
    id: "v4",
    providerId: "p1",
    name: "Honda Civic RS 2023",
    brand: "Honda",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 110000,
    pricePerDay: 1050000,
    image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Phong cách thể thao cuốn hút, động cơ 1.5L VTEC Turbo bốc và đầm chắc, hệ thống an toàn Honda SENSING hiện đại.",
    features: ["Honda SENSING", "Lẫy chuyển số vô lăng", "Màn hình 9 inch không dây", "Dàn âm thanh Bose 12 loa"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v5",
    providerId: "p3",
    name: "Honda CR-V 2024",
    brand: "Honda",
    type: "SUV",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 145000,
    pricePerDay: 1350000,
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    location: "Đà Nẵng",
    description: "SUV 7 chỗ thế hệ mới, không gian rộng rãi, trang bị cửa sổ trời Panorama toàn cảnh và gói trợ lái chủ động.",
    features: ["Cửa sổ trời Panorama", "Honda CONNECT", "Sạc không dây", "Cốp điện thông minh"],
    status: "approved",
    rating: 4.8,
  },
  {
    id: "v6",
    providerId: "p2",
    name: "Honda City RS 2024",
    brand: "Honda",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 75000,
    pricePerDay: 700000,
    image: "https://images.unsplash.com/photo-1592853625597-7d17be820d0c?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "Thiết kế trẻ trung, nội thất rộng rãi nhất phân khúc B, ghế da viền chỉ đỏ thể thao và kết nối điện thoại tiện lợi.",
    features: ["Honda SENSING", "Khởi động từ xa", "Ghế da lộn thể thao", "Camera lùi 3 góc"],
    status: "approved",
    rating: 4.6,
  },
  {
    id: "v7",
    providerId: "p1",
    name: "Mazda 3 Premium 2023",
    brand: "Mazda",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 90000,
    pricePerDay: 850000,
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Ngôn ngữ thiết kế KODO tinh xảo như một tác phẩm điêu khắc, nội thất bọc da cao cấp chuẩn xe sang châu Âu.",
    features: ["Màn hình HUD hiển thị kính lái", "Gói an toàn i-Activsense", "Ghế lái nhớ 2 vị trí", "Đèn pha thích ứng ALH"],
    status: "approved",
    rating: 4.7,
  },
  {
    id: "v8",
    providerId: "p2",
    name: "Mazda CX-5 2.0 Premium 2024",
    brand: "Mazda",
    type: "Crossover",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 110000,
    pricePerDay: 1000000,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "Mẫu CUV 5 chỗ bán chạy nhất thị trường, khoang lái cách âm hoàn hảo, trải nghiệm lái đầm chắc và thời thượng.",
    features: ["10 loa Bose cao cấp", "Camera 360", "Cửa sổ trời", "Cảnh báo chệch làn đường"],
    status: "approved",
    rating: 4.8,
  },
  {
    id: "v9",
    providerId: "p1",
    name: "VinFast VF3 2024",
    brand: "VinFast",
    type: "Mini SUV điện",
    seats: 4,
    transmission: "Số tự động",
    fuel: "Điện",
    pricePerHour: 50000,
    pricePerDay: 450000,
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Xe điện mini siêu cá tính, luồn lách linh hoạt trên phố đông, sạc nhanh tiện lợi, chi phí năng lượng siêu rẻ.",
    features: ["Màn hình trung tâm 10 inch", "Phanh tái sinh", "Cảm biến lùi", "Gầm cao 191mm"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v10",
    providerId: "p1",
    name: "VinFast VF6 Plus 2024",
    brand: "VinFast",
    type: "Crossover điện",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Điện",
    pricePerHour: 90000,
    pricePerDay: 850000,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Crossover điện thông minh công suất 201 mã lực, hỗ trợ trợ lý ảo tiếng Việt Vivi, quãng đường chạy 381km sau mỗi lần sạc.",
    features: ["Trợ lý ảo thông minh Vivi", "ADAS lái tự động cấp 2", "Màn hình cảm ứng 12.9 inch", "Cập nhật phần mềm OTA"],
    status: "approved",
    rating: 4.8,
  },
  {
    id: "v11",
    providerId: "p2",
    name: "VinFast VF8 Plus 2024",
    brand: "VinFast",
    type: "SUV điện",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Điện",
    pricePerHour: 150000,
    pricePerDay: 1450000,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "SUV điện 2 mô-tơ 402 mã lực dẫn động 4 bánh toàn thời gian (AWD), tăng tốc 0-100km/h trong 5.5s, nội thất sang trọng chuẩn châu Âu.",
    features: ["Dẫn động 4 bánh AWD", "Hệ thống tự lái ADAS cao cấp", "Ghế sưởi và làm mát", "Trợ lý ảo Vivi"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v12",
    providerId: "p1",
    name: "VinFast VF9 Plus 2024",
    brand: "VinFast",
    type: "SUV điện",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Điện",
    pricePerHour: 240000,
    pricePerDay: 2300000,
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "SUV full-size điện hạng sang cỡ lớn, hàng ghế thương gia tích hợp massage làm mát, trần kính toàn cảnh cách nhiệt chống UV.",
    features: ["Ghế thương gia massage đa điểm", "Trần kính toàn cảnh", "Màn hình giải trí 15.6 inch", "Cửa hít tự động"],
    status: "approved",
    rating: 5.0,
  },
  {
    id: "v13",
    providerId: "p3",
    name: "Hyundai Accent 2024",
    brand: "Hyundai",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 70000,
    pricePerDay: 600000,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    location: "Đà Nẵng",
    description: "Sedan gia đình thế hệ hoàn toàn mới, kiểu dáng hiện đại góc cạnh, trang bị gói Hyundai SmartSense, cốp thông minh tự mở.",
    features: ["Hyundai SmartSense", "Khởi động từ xa", "Cửa sổ trời", "Điều hòa tự động khử ion"],
    status: "approved",
    rating: 4.7,
  },
  {
    id: "v14",
    providerId: "p1",
    name: "Hyundai Tucson 1.6 Turbo 2024",
    brand: "Hyundai",
    type: "Crossover",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 120000,
    pricePerDay: 1100000,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Thiết kế tương lai Parametric Dynamic, động cơ SmartStream 1.6 Turbo mạnh mẽ kèm dẫn động HTRAC 4 bánh.",
    features: ["Cần số điện tử dạng nút bấm", "Camera 360", "Ghế sưởi và làm mát", "Dẫn động HTRAC 4WD"],
    status: "approved",
    rating: 4.8,
  },
  {
    id: "v15",
    providerId: "p2",
    name: "Hyundai Santa Fe 2024",
    brand: "Hyundai",
    type: "SUV",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 180000,
    pricePerDay: 1700000,
    image: "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "Thế hệ Santa Fe hình khối vuông vức cá tính, nội thất ngập tràn công nghệ, 2 màn hình cong 12.3 inch siêu nét.",
    features: ["Màn hình cong kép Panoramic 12.3 inch", "Sạc không dây kép", "Gói hỗ trợ lái SmartSense", "Cốp mở siêu rộng"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v16",
    providerId: "p1",
    name: "Kia Carnival Signature 2024",
    brand: "Kia",
    type: "MPV",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Dầu diesel",
    pricePerHour: 200000,
    pricePerDay: 1900000,
    image: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Chuyên cơ mặt đất 7 chỗ VIP, hàng ghế 2 chỉnh điện đa hướng kèm đệm đỡ bắp chân, cửa lùa điện thông minh 2 bên.",
    features: ["Ghế VIP thương gia đệm bắp chân", "Cửa lùa điện 2 bên", "12 Loa Bose âm thanh vòm", "Cửa sổ trời đôi"],
    status: "approved",
    rating: 5.0,
  },
  {
    id: "v17",
    providerId: "p2",
    name: "Kia Seltos GT-Line 2024",
    brand: "Kia",
    type: "Crossover",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 95000,
    pricePerDay: 850000,
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "CUV đô thị trẻ trung thể thao, động cơ SmartStream 1.5 Turbo khỏe khoắn, phanh tay điện tử Auto Hold tiện ích.",
    features: ["Phanh tay điện tử & Auto Hold", "Màn hình giải trí liền khối 10.25 inch", "Làm mát ghế trước", "Gói an toàn ADAS"],
    status: "approved",
    rating: 4.7,
  },
  {
    id: "v18",
    providerId: "p1",
    name: "Ford Everest Titanium+ 4x4 2024",
    brand: "Ford",
    type: "SUV",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Dầu diesel",
    pricePerHour: 160000,
    pricePerDay: 1550000,
    image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Vua địa hình SUV 7 chỗ cơ bắp Mỹ, động cơ 2.0L Bi-Turbo cùng hộp số tự động 10 cấp êm ái, 6 chế độ lái đa địa hình.",
    features: ["Dẫn động 4x4 hai cầu điện tử", "Hộp số 10 cấp", "Màn hình dọc 12 inch SYNC 4", "Hỗ trợ đỗ xe tự động"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v19",
    providerId: "p3",
    name: "Ford Ranger Raptor 2024",
    brand: "Ford",
    type: "Bán tải",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Dầu diesel",
    pricePerHour: 180000,
    pricePerDay: 1700000,
    image: "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=800&q=80",
    location: "Đà Nẵng",
    description: "Siêu bán tải hiệu năng cao, giảm xóc FOX 2.5 Live Valve đỉnh cao, chế độ lái Baja chạy cát sỏi sa mạc cực phấn khích.",
    features: ["Giảm xóc FOX Live Valve", "Chế độ chạy Baja", "Nội thất thể thao thêu chỉ đỏ", "Lốp địa hình BFGoodrich"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v20",
    providerId: "p1",
    name: "Mercedes-Benz C300 AMG 2023",
    brand: "Mercedes-Benz",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 250000,
    pricePerDay: 2400000,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "Sedan thể thao sang trọng nước Đức, đèn Digital Light chiếu sáng 650m, nội thất đèn viền LED 64 màu, âm thanh Burmester 3D.",
    features: ["Đèn chiếu sáng Digital Light", "Âm thanh Burmester 3D 15 loa", "Đèn viền nội thất 64 màu", "Camera 360 độ 3D"],
    status: "approved",
    rating: 5.0,
  },
  {
    id: "v21",
    providerId: "p2",
    name: "Mercedes-Benz GLC 300 4MATIC 2024",
    brand: "Mercedes-Benz",
    type: "SUV",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 290000,
    pricePerDay: 2800000,
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "SUV sang trọng hàng đầu, dẫn động 4 bánh 4MATIC danh tiếng, chế độ Off-road với tính năng nắp capo trong suốt (Transparent Bonnet).",
    features: ["Nắp capo trong suốt Off-road", "Dẫn động 4MATIC", "Gói ngoại thất thể thao AMG", "Màn hình cảm ứng 11.9 inch nghiêng"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v22",
    providerId: "p2",
    name: "BMW 330i M Sport 2023",
    brand: "BMW",
    type: "Sedan",
    seats: 5,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 260000,
    pricePerDay: 2500000,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "Chiếc sedan chuẩn mực của cảm giác lái thuần chất thể thao, phân bổ trọng lượng hoàn hảo 50:50, phanh và treo M Sport sắc bén.",
    features: ["Màn hình cong BMW Curved Display", "Treo & Phanh thể thao M Sport", "Dàn âm thanh Harman Kardon", "Trợ lý ảo BMW Intelligent"],
    status: "approved",
    rating: 4.9,
  },
  {
    id: "v23",
    providerId: "p1",
    name: "BMW X5 xDrive40i 2024",
    brand: "BMW",
    type: "SUV",
    seats: 7,
    transmission: "Số tự động",
    fuel: "Xăng",
    pricePerHour: 380000,
    pricePerDay: 3600000,
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    location: "Hà Nội",
    description: "SUV SAV hạng sang đầu bảng của BMW, động cơ 6 xi-lanh thẳng hàng TwinPower Turbo 381 mã lực, nội thất ốp pha lê Crafted Clarity.",
    features: ["Cần số pha lê Crafted Clarity", "Hệ thống treo khí nén 2 cầu", "Cửa sổ trời Panorama Sky Lounge", "Âm thanh Harman Kardon"],
    status: "approved",
    rating: 5.0,
  },
  {
    id: "v24",
    providerId: "p2",
    name: "Porsche Taycan 4S 2024",
    brand: "Porsche",
    type: "Sedan",
    seats: 4,
    transmission: "Số tự động",
    fuel: "Điện",
    pricePerHour: 650000,
    pricePerDay: 6000000,
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80",
    location: "TP. Hồ Chí Minh",
    description: "Siêu phẩm sedan thể thao thuần điện của Porsche, công suất 530 mã lực Launch Control, tăng tốc 0-100km/h trong 4.0s.",
    features: ["Hệ thống sạc siêu nhanh 800V", "Porsche Active Suspension Management", "Âm thanh vòm BOSE", "Màn hình cong Porsche Advanced Cockpit"],
    status: "approved",
    rating: 5.0,
  },
];

export const seedOrders = [
  {
    id: "o1",
    customerId: "c1",
    vehicleId: "v1",
    startDate: "2026-08-25",
    endDate: "2026-08-27",
    totalPrice: 1300000,
    status: "completed",
    paymentStatus: "paid",
    createdAt: "2026-08-15",
  },
  {
    id: "o2",
    customerId: "c1",
    vehicleId: "v4",
    startDate: "2026-08-20",
    endDate: "2026-08-22",
    totalPrice: 2100000,
    status: "completed",
    paymentStatus: "paid",
    createdAt: "2026-08-18",
  },
];

export const seedPromotions = [
  {
    id: "pr1",
    providerId: "p1",
    code: "MORENT10",
    discountPercent: 10,
    description: "Giảm 10% cho mọi chuyến đi trải nghiệm đầu tiên",
    expiryDate: "2026-12-31",
  },
  {
    id: "pr2",
    providerId: "p1",
    code: "SUMMER15",
    discountPercent: 15,
    description: "Ưu đãi mùa hè giảm 15% cho dòng xe SUV du lịch",
    expiryDate: "2026-09-30",
  },
  {
    id: "pr3",
    providerId: "p2",
    code: "VINFAST20",
    discountPercent: 20,
    description: "Giảm 20% khi thuê xe điện VinFast bảo vệ môi trường",
    expiryDate: "2026-11-30",
  },
];

export const seedNotifications = [
  {
    id: "n1",
    audience: "customer",
    title: "Chào mừng bạn đến với Morent!",
    message: "Khám phá ngay hơn 20+ dòng xe đa dạng từ phổ thông đến hạng sang có sẵn trong khu vực của bạn.",
    createdAt: "2026-08-25",
  },
];

export const seedSupportTickets = [
  {
    id: "s1",
    fromRole: "customer",
    fromId: "c1",
    subject: "Hỏi về thủ tục nhận xe tại sân bay",
    message: "Tôi có thể yêu cầu giao nhận xe trực tiếp tại sảnh ga đến sân bay Nội Bài được không?",
    status: "resolved",
    reply: "Chào bạn, Morent hỗ trợ giao nhận xe tận nơi tại tất cả các sân bay lớn (Nội Bài, Tân Sơn Nhất, Đà Nẵng). Khi đặt xe bạn chỉ cần ghi chú sảnh đến.",
    createdAt: "2026-08-20",
  },
];

export const seedStaff = [
  { id: "st1", name: "Admin gốc", email: "admin@morent.vn", permission: "full", createdAt: "2026-01-01" },
];

export const seedReviews = [
  {
    id: "r1",
    customerId: "c1",
    vehicleId: "v1",
    orderId: "o1",
    rating: 5,
    comment: "Xe rất mới và sạch sẽ, máy êm, điều hoà mát sâu. Chủ xe giao xe đúng giờ và nhiệt tình hướng dẫn!",
    providerReply: "Cảm ơn bạn đã tin tưởng Hanoi Auto Rentals. Rất mong được phục vụ bạn trong những chuyến đi tới!",
    createdAt: "2026-08-28",
  },
  {
    id: "r2",
    customerId: "c2",
    vehicleId: "v4",
    orderId: "o2",
    rating: 5,
    comment: "Honda Civic RS chạy cực bốc và cảm giác lái rất phấn khích, âm thanh Bose nghe nhạc cực đã.",
    providerReply: "Cảm ơn anh Hoàng đã trải nghiệm dịch vụ xe bên em!",
    createdAt: "2026-08-22",
  },
];
